// <auto-generated />
namespace AutoserviceManagerWorkplace.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeCarOwnersfromOrderList3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeCarOwnersfromOrderList3));
        
        string IMigrationMetadata.Id
        {
            get { return "201704251028017_remove CarOwners from OrderList3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
